[package]
name = "weo"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
reqwest = { version = "0.12.15", features = ["blocking"] }
tempfile = "3.20.0"

[[bin]]
name = "weo"
path = "src/main.rs"
