# Create new environment instances
---
- name: adding user '{{ instance_user_name }}' for developer
  user:
    name: '{{ instance_user_name }}'
    password: '{{ instance_user_password }}'
    shell: /bin/bash
    state: present

- name: adding user '{{ instance_user_name }}' to group sudo$
  when: {{ instance_user_sudo }}
  user:
    name: '{{ instance_user_name }}'
    groups: sudo
    append: yes