---
# Run this playbook on all environments as root.
# All commandos will be executed with root permissions except if specified
# otherwise
- hosts: zephyr-env
  become: true
  # Set the variable file and the vault file to be used
  vars_files:
    - vars/main.yml
    - vault/main.yml
  handlers:
    - name: Reload udev configuration
      command: udevadm control --reload

  # Include the correct play dependent on the run_option
  tasks:
    - name: Create
      include_tasks: "tasks/create.yml"
      when: run_option == "create"

    - name: Delete
      include_tasks: "tasks/delete.yml"
      when: run_option == "delete"

    - name: Restart
      include_tasks: "tasks/restart.yml"
      when: run_option == "restart"
