# Inventory of zephyr-env instances
---
all:
  hosts:
    weo01:
      ansible_host:                    "{{ weo_host }}"
      ansible_port:                    "{{ weo_port }}"
      ansible_user:                    "{{ weo_user }}"
      ansible_sudo_pass:               "{{ weo_password }}" #ToDo: Use vault
  children:
    weo:
      hosts:
        weo01: