---
# Run this playbook on all ansible as root.
# All commandos will be executed with root permissions except if specified
# otherwise
- hosts: weo
  become: true
  #Set the variable file and the vault file to be used
  vars_files:
    - vars/main.yml
    - vault/main.yml

  # Include the correct play dependent on the run_option
  tasks:
    - name: Create
      include_tasks: "tasks/create.yml"
      when: run_option == "create"

    - name: Remove
      include_tasks: "tasks/remove.yml"
      when: run_option == "remove"

    - name: Export
      include_tasks: "tasks/export.yml"
      when: run_option == "export"

    - name: Import
      include_tasks: "tasks/import.yml"
      when: run_option == "import"
